language: ruby
rvm:
- 2.6.0

jdk:
- oraclejdk8

install:
- bundle install
- pip install --user html5validator
- pip install --user yamale
- npm install
- pip install --user yamllint

script:
- bundle exec jekyll build
- htmlproofer --disable-external --allow-hash-href ./_site
- html5validator --root _site/
- yamale -s schemas/administrations.yml _data/administrations
- yamale -s schemas/code_administration.yml _data/code/administrations
- yamale -s schemas/code_code.yml _data/code/releases/
- yamale -s schemas/software_administration.yml _data/software/**/administrations
- yamale -s schemas/software_software.yml _data/software/**/*.yml
- yamale -s schema/standards_administration.yml _data/standards/**/administrations
- yamale -s schema/standards_standards.yml _data/standards/**/*.yml
- npm run lint
- yamllint -d configYamlLint.yml _data


sudo: false