# Site settings
baseurl: "/ore-ero" # the subpath of your site, e.g. /blog
url: "https://canada-ca.github.io/ore-ero" # the base hostname & protocol for your site
github_username: fredericlestage-vdm # CHANGE HERE FOR YOUR GITHUB USERNAME
github_repository: ore-ero
prbot_url: "http://localhost:3000" # CHANGE HERE IF YOU USE A CUSTOM PORT NUMBER

wet_cdts_hosturl: "https://www.canada.ca/etc/designs/canada/cdts/gcweb"
wet_cdts_version: "v4_0_30"

# Build settings
markdown: kramdown
include: ["_pages", "_json"]
